let ourdays_gallery = document.querySelector('.ourdays__gallery')

const ourdaysImages = [
    '../../src/images/outdays/days1.jpeg',
    '../../src/images/outdays/days2.jpeg',
    '../../src/images/outdays/days3.jpeg',
    '../../src/images/outdays/days4.jpeg',
    '../../src/images/outdays/days5.jpeg',
    '../../src/images/outdays/days6.jpeg',
    '../../src/images/outdays/days7.jpeg',
    '../../src/images/outdays/days8.jpeg',
    '../../src/images/outdays/days10.jpeg',
    '../../src/images/outdays/days11.jpeg',
    '../../src/images/outdays/days12.jpeg',
    '../../src/images/outdays/days13.jpeg',
    '../../src/images/outdays/days14.jpeg',
    '../../src/images/outdays/days15.jpeg',
    '../../src/images/outdays/days16.jpeg',
    '../../src/images/outdays/days17.jpeg',
    '../../src/images/outdays/days18.jpeg',
    '../../src/images/outdays/days19.jpeg',
    '../../src/images/outdays/days20.jpeg',
    '../../src/images/outdays/days21.jpeg',
    '../../src/images/outdays/days22.jpeg',
    '../../src/images/outdays/days23.jpeg',
    '../../src/images/outdays/days24.jpeg',
    '../../src/images/outdays/days25.jpeg',
    '../../src/images/outdays/days26.jpeg',
    '../../src/images/outdays/days27.jpeg',
    '../../src/images/outdays/days28.jpeg',
    '../../src/images/outdays/days29.jpeg',
    '../../src/images/outdays/days30.jpeg',
    '../../src/images/outdays/days31.jpeg',
    '../../src/images/outdays/days32.jpeg',
    '../../src/images/outdays/days33.jpeg',
    '../../src/images/outdays/days34.jpeg',
    '../../src/images/outdays/days35.jpeg',
    '../../src/images/outdays/days36.jpeg',
    '../../src/images/outdays/days37.jpeg',
    '../../src/images/outdays/days38.jpeg',
    '../../src/images/outdays/days39.jpeg',
    '../../src/images/outdays/days39.jpeg',
    '../../src/images/outdays/days39.jpeg',
    '../../src/images/outdays/days40.jpeg',
    '../../src/images/outdays/days41.jpeg',
    '../../src/images/outdays/days42.jpeg',
    '../../src/images/outdays/days43.jpeg',
    '../../src/images/outdays/days44.jpeg',
    '../../src/images/outdays/days45.jpeg',
    '../../src/images/outdays/days46.jpeg',
]

showGallery(ourdaysImages, ourdays_gallery)